on: push
name: Push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.6.0
      with:
        #select: E3,E4,E5,E7,W6,F,B,G0
        maxlinelength: 500
        repotoken: ${{ secrets.GITHUB_TOKEN }}
